FROM node:18

WORKDIR /usr/src/app

COPY texts/node/package*.json ./texts/node/
COPY framework/node ./framework/node

WORKDIR /usr/src/app/framework/node/host
RUN npm install

WORKDIR /usr/src/app/texts/node
RUN npm install
#RUN npm ci --only=production
WORKDIR /usr/src/app

COPY texts/node/app ./texts/node/app/
COPY texts/node/app/config/config-dev.js ./texts/node/app/config/config.js

WORKDIR /usr/src/app/texts/node
CMD [ "npm", "run", "start:prod" ]
