FROM node:18

WORKDIR /usr/src/app

COPY node/package*.json ./

RUN npm install
#RUN npm ci --only=production

COPY node/app app/
COPY node/app/config/config-dev.js app/config/config.js

CMD [ "npm", "run", "start:prod" ]
