FROM node:18

WORKDIR /usr/src/app
COPY texts/node/package*.json ./texts/node/
COPY framework/node/host/package*.json ./framework/node/host/
COPY texts/config-production.json ./texts/config.json

WORKDIR /usr/src/app/framework/node/host
RUN npm ci --only=production

WORKDIR /usr/src/app
COPY framework/node ./framework/node/

WORKDIR /usr/src/app/texts/node
RUN npm ci --only=production
COPY texts/node/app ./app/

CMD [ "npm", "run", "start:prod" ]
