FROM node:18

WORKDIR /usr/src/app

COPY texts-node/package*.json ./

#RUN npm install
RUN npm ci --only=production

COPY texts-node/app app/
COPY texts-node/app/config/config-production.js app/config/config.js

CMD [ "npm", "run", "start:prod" ]
