version: '3.4'

networks:
  typingrealm-net:
  typingrealm-data-net:
  typingrealm-texts-net:

services:
  typingrealm-identityserver:
    image: ${DOCKER_REGISTRY-}typingrealm-identityserver
    container_name: typingrealm-identityserver
    networks:
      - typingrealm-net
    build:
      context: .
      dockerfile: TypingRealm.IdentityServer.Host/Dockerfile
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 750m
    env_file:
      - .env.prod

  typingrealm-profiles:
    image: ${DOCKER_REGISTRY-}typingrealm-profiles
    container_name: typingrealm-profiles
    networks:
      - typingrealm-net
    build:
      context: .
      dockerfile: TypingRealm.Profiles.Api/Dockerfile
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 750m
    env_file:
      - .env.prod

  typingrealm-data:
    image: ${DOCKER_REGISTRY-}typingrealm-data
    container_name: typingrealm-data
    networks:
      - typingrealm-net
      - typingrealm-data-net
    build:
      context: .
      dockerfile: TypingRealm.Data.Api/Dockerfile
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 750m
    env_file:
      - .env.prod
      - .env.prod.data

  typingrealm-texts:
    image: ${DOCKER_REGISTRY-}typingrealm-texts
    container_name: typingrealm-texts
    networks:
      - typingrealm-net
      - typingrealm-texts-net
    build:
      context: .
      dockerfile: TypingRealm.Texts.Api/Dockerfile
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 750m
    env_file:
      - .env.prod
      - .env.prod.texts

  # === Infrastructure ===

  typingrealm-redis:
    image: redis
    container_name: typingrealm-redis
    networks:
      - typingrealm-net
    volumes:
      - ./infrastructure-data/prod/shared/redis:/data
    restart: unless-stopped
    mem_limit: 2g
    mem_reservation: 1.75g
    env_file:
      - .env.prod

  typingrealm-data-redis:
    image: redis
    container_name: typingrealm-data-redis
    networks:
      - typingrealm-data-net
    volumes:
      - ./infrastructure-data/prod/data/redis:/data
    restart: unless-stopped
    mem_limit: 2g
    mem_reservation: 1.75g
    env_file:
      - .env.prod
      - .env.prod.data

  typingrealm-data-postgres:
    image: postgres
    container_name: typingrealm-data-postgres
    networks:
      - typingrealm-data-net
    volumes:
      - ./infrastructure-data/prod/data/postgres:/var/lib/postgresql/data
    restart: unless-stopped
    mem_limit: 2g
    mem_reservation: 1.75g
    env_file:
      - .env.prod
      - .env.prod.data

  typingrealm-caddy:
    image: caddy
    container_name: typingrealm-caddy
    networks:
      - typingrealm-net
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./reverse-proxy/Caddyfile.prod:/etc/caddy/Caddyfile
      - ./infrastructure-data/prod/caddy_data:/data
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 750m
    env_file:
      - .env.prod

  typingrealm-web-ui:
    image: ${DOCKER_REGISTRY-}typingrealm-web-ui
    container_name: typingrealm-web-ui
    networks:
      - typingrealm-net
    build:
      context: ./typingrealm-web
      dockerfile: Dockerfile
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 750m
    env_file:
      - .env.prod
