version: '3.4'

networks:
  debug-typingrealm-net:

services:
  debug-typingrealm-identityserver:
    image: ${DOCKER_REGISTRY-}debug-typingrealm-identityserver
    container_name: debug-typingrealm-identityserver
    networks:
      - debug-typingrealm-net
    ports:
      - 30000:80
    build:
      context: .
      dockerfile: TypingRealm.IdentityServer.Host/Dockerfile
    env_file:
      - .env.debug

  debug-typingrealm-profiles:
    image: ${DOCKER_REGISTRY-}debug-typingrealm-profiles
    container_name: debug-typingrealm-profiles
    networks:
      - debug-typingrealm-net
    ports:
      - 30103:80
    build:
      context: .
      dockerfile: TypingRealm.Profiles.Api/Dockerfile
    env_file:
      - .env.debug

  debug-typingrealm-data:
    image: ${DOCKER_REGISTRY-}debug-typingrealm-data
    container_name: debug-typingrealm-data
    networks:
      - debug-typingrealm-net
    ports:
      - 30400:80
    build:
      context: .
      dockerfile: TypingRealm.Data.Api/Dockerfile
    env_file:
      - .env.debug
      - .env.debug.data

  debug-typingrealm-texts:
    image: ${DOCKER_REGISTRY-}debug-typingrealm-texts
    container_name: debug-typingrealm-texts
    networks:
      - debug-typingrealm-net
    ports:
      - 30401:80
    build:
      context: .
      dockerfile: TypingRealm.Texts.Api/Dockerfile
    env_file:
      - .env.debug
      - .env.debug.texts

  debug-typingrealm-library:
    image: ${DOCKER_REGISTRY-}debug-typingrealm-library
    container_name: debug-typingrealm-library
    networks:
      - debug-typingrealm-net
    ports:
      - 30402:80
    build:
      context: .
      dockerfile: TypingRealm.Library.Api/Dockerfile
    env_file:
      - .env.debug
      - .env.debug.library
    mem_limit: 500m
    mem_reservation: 350m
