version: '3.4'

# TODO: Make sure networks don't collaps in PROD and DEV flows.
# Needs to be created separately if you use production yml.
networks:
  typingrealm-net:
    external:
      name: typingrealm-net

services:
  tyr-caddy:
    image: caddy
    container_name: tyr-caddy
    networks:
      - typingrealm-net
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    volumes:
      - ./reverse-proxy/Caddyfile:/etc/caddy/Caddyfile
      - ./reverse-proxy/caddy_data:/data

  typingrealm-identityserver:
    restart: unless-stopped

  typingrealm-profiles:
    restart: unless-stopped

  typingrealm-data:
    restart: unless-stopped

  typingrealm-web-typing-page:
    image: ${DOCKER_REGISTRY-}typingrealm-web-typing-page
    container_name: typingrealm-web-typing-page
    networks:
      - typingrealm-net
    build:
      context: ./typingrealm-web
      dockerfile: Dockerfile
