version: '3.4'

services:
  typingrealm-identityserver:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "30000:80"

  typingrealm-profiles:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  typingrealm-data:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
