version: '3.4'

networks:
  local-typingrealm-net:
  local-typingrealm-data-net:
  local-typingrealm-texts-net:

services:
  local-typingrealm-identityserver:
    image: ${DOCKER_REGISTRY-}local-typingrealm-identityserver
    container_name: local-typingrealm-identityserver
    networks:
      - local-typingrealm-net
    build:
      context: .
      dockerfile: TypingRealm.IdentityServer.Host/Dockerfile
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 750m
    env_file:
      - .env.local

  local-typingrealm-profiles:
    image: ${DOCKER_REGISTRY-}local-typingrealm-profiles
    container_name: local-typingrealm-profiles
    networks:
      - local-typingrealm-net
    build:
      context: .
      dockerfile: TypingRealm.Profiles.Api/Dockerfile
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 750m
    env_file:
      - .env.local

  local-typingrealm-data:
    image: ${DOCKER_REGISTRY-}local-typingrealm-data
    container_name: local-typingrealm-data
    networks:
      - local-typingrealm-net
      - local-typingrealm-data-net
    build:
      context: .
      dockerfile: TypingRealm.Data.Api/Dockerfile
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 750m
    env_file:
      - .env.local
      - .env.local.data

  local-typingrealm-texts:
    image: ${DOCKER_REGISTRY-}local-typingrealm-texts
    container_name: local-typingrealm-texts
    networks:
      - local-typingrealm-net
      - local-typingrealm-texts-net
    build:
      context: .
      dockerfile: TypingRealm.Texts.Api/Dockerfile
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 750m
    env_file:
      - .env.local
      - .env.local.texts

  # === Infrastructure ===

  local-typingrealm-redis:
    image: redis
    container_name: local-typingrealm-redis
    networks:
      - local-typingrealm-net
    volumes:
      - ./infrastructure-data/local/shared/redis:/data
    restart: unless-stopped
    mem_limit: 2g
    mem_reservation: 1.75g
    env_file:
      - .env.local

  local-typingrealm-data-redis:
    image: redis
    container_name: local-typingrealm-data-redis
    networks:
      - local-typingrealm-data-net
    volumes:
      - ./infrastructure-data/local/data/redis:/data
    restart: unless-stopped
    mem_limit: 2g
    mem_reservation: 1.75g
    env_file:
      - .env.local
      - .env.local.data

  local-typingrealm-texts-redis:
    image: redis
    container_name: local-typingrealm-texts-redis
    networks:
      - local-typingrealm-texts-net
    volumes:
      - ./infrastructure-data/local/texts/redis:/data
    restart: unless-stopped
    mem_limit: 2g
    mem_reservation: 1.75g
    env_file:
      - .env.local
      - .env.local.texts

  local-typingrealm-data-postgres:
    image: postgres
    container_name: local-typingrealm-data-postgres
    networks:
      - local-typingrealm-data-net
    volumes:
      - ./infrastructure-data/local/data/postgres:/var/lib/postgresql/data
    restart: unless-stopped
    mem_limit: 2g
    mem_reservation: 1.75g
    env_file:
      - .env.local
      - .env.local.data

  local-typingrealm-caddy:
    image: caddy
    container_name: local-typingrealm-caddy
    networks:
      - local-typingrealm-net
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    volumes:
      - ./reverse-proxy/Caddyfile.local:/etc/caddy/Caddyfile
      - ./infrastructure-data/local/caddy_data:/data
    mem_limit: 1g
    mem_reservation: 750m
    env_file:
      - .env.local
