version: '3.4'

networks:
  typingrealm-net:
  local-tyr_local-typingrealm-net:
    external: true
  dev-tyr_dev-typingrealm-net:
    external: true

services:
  typingrealm-identityserver:
    image: ${DOCKER_REGISTRY-}typingrealm-identityserver
    container_name: typingrealm-identityserver
    networks:
      - typingrealm-net
    build:
      context: .
      dockerfile: TypingRealm.IdentityServer.Host/Dockerfile
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 750m
    env_file:
      - .env.prod

  typingrealm-profiles:
    image: ${DOCKER_REGISTRY-}typingrealm-profiles
    container_name: typingrealm-profiles
    networks:
      - typingrealm-net
    build:
      context: .
      dockerfile: TypingRealm.Profiles.Api/Dockerfile
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 750m
    env_file:
      - .env.prod

  typingrealm-data:
    image: ${DOCKER_REGISTRY-}typingrealm-data
    container_name: typingrealm-data
    networks:
      - typingrealm-net
    build:
      context: .
      dockerfile: TypingRealm.Data.Api/Dockerfile
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 750m
    env_file:
      - .env.prod

  # === Infrastructure ===

  typingrealm-postgres:
    image: postgres
    container_name: typingrealm-postgres
    networks:
      - typingrealm-net
    # Should be disabled in production. This is for conveniency of connecting to prod DB.
    ports:
      - 5430:5432
    volumes:
      - ./infrastructure-data/prod/postgres:/var/lib/postgresql/data
    restart: unless-stopped
    mem_limit: 2g
    mem_reservation: 1.75g
    env_file:
      - .env.prod

  typingrealm-redis:
    image: redis
    container_name: typingrealm-redis
    networks:
      - typingrealm-net
    # Should be disabled in production. This is for conveniency of connecting to prod DB.
    ports:
      - 6370:6379
    volumes:
      - ./infrastructure-data/prod/redis:/data
    restart: unless-stopped
    mem_limit: 2g
    mem_reservation: 1.75g
    env_file:
      - .env.prod

  typingrealm-data-redis:
    image: redis
    container_name: typingrealm-data-redis
    networks:
      - typingrealm-net
    # Should be disabled in production. This is for conveniency of connecting to prod DB.
    ports:
      - 34370:6379
    volumes:
      - ./infrastructure-data/prod/data-redis:/data
    restart: unless-stopped
    mem_limit: 2g
    mem_reservation: 1.75g
    env_file:
      - .env.prod

  # This is Caddy both for PROD, DEV and LOCAL routing.
  # In the final PROD configuration another Caddyfile should be deployed.
  typingrealm-caddy:
    image: caddy
    container_name: typingrealm-caddy
    networks:
      - typingrealm-net
      - local-tyr_local-typingrealm-net
      - dev-tyr_dev-typingrealm-net
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./reverse-proxy/Caddyfile.host:/etc/caddy/Caddyfile
      - ./infrastructure-data/prod/caddy_data:/data
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 750m
    env_file:
      - .env.prod

  # Simple local UI test page to facilitate BackEnd development.
  typingrealm-web-ui:
    image: ${DOCKER_REGISTRY-}typingrealm-web-ui
    container_name: typingrealm-web-ui
    networks:
      - typingrealm-net
    build:
      context: ./typingrealm-web
      dockerfile: Dockerfile
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 750m
    env_file:
      - .env.prod
