version: '3.4'

services:
  typingrealm-identityserver:
    image: ${DOCKER_REGISTRY-}typingrealm-identityserver:dev
    container_name: typingrealm-identityserver-dev
    ports:
      - "30000:80"
    env_file:
      - .env.dev

  typingrealm-profiles:
    image: ${DOCKER_REGISTRY-}typingrealm-profiles:dev
    container_name: typingrealm-profiles-dev
    ports:
      - "30103:80"
    env_file:
      - .env.dev

  typingrealm-data:
    image: ${DOCKER_REGISTRY-}typingrealm-data:dev
    container_name: typingrealm-data-dev
    ports:
      - "30400:80"
    env_file:
      - .env.dev
