version: '3.4'

networks:
  typingrealm-net:

services:
  typingrealm-identityserver:
    image: ${DOCKER_REGISTRY-}typingrealm-identityserver
    container_name: typingrealm-identityserver
    networks:
      - typingrealm-net
    build:
      context: .
      dockerfile: TypingRealm.IdentityServer.Host/Dockerfile

  typingrealm-profiles:
    image: ${DOCKER_REGISTRY-}typingrealm-profiles
    container_name: typingrealm-profiles
    networks:
      - typingrealm-net
    build:
      context: .
      dockerfile: TypingRealm.Profiles.Api/Dockerfile
    environment:
      - SERVICE_AUTHORITY=http://typingrealm-identityserver/
      - PROFILES_URL=http://typingrealm-profiles
      - DATA_URL=http://typingrealm-data

  typingrealm-data:
    image: ${DOCKER_REGISTRY-}typingrealm-data
    container_name: typingrealm-data
    networks:
      - typingrealm-net
    build:
      context: .
      dockerfile: TypingRealm.Data.Api/Dockerfile
    environment:
      - SERVICE_AUTHORITY=http://typingrealm-identityserver/
      - PROFILES_URL=http://typingrealm-profiles
      - DATA_URL=http://typingrealm-data
