version: '3.4'

services:
  typingrealm-caddy:
    image: caddy
    container_name: typingrealm-caddy
    networks:
      - typingrealm-net
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    volumes:
      - ./reverse-proxy/Caddyfile:/etc/caddy/Caddyfile
      - ./reverse-proxy/caddy_data:/data
    mem_limit: 1g
    mem_reservation: 750m

  typingrealm-identityserver:
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 750m

  typingrealm-profiles:
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 750m

  typingrealm-data:
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 750m

  typingrealm-web-ui:
    image: ${DOCKER_REGISTRY-}typingrealm-web-ui
    container_name: typingrealm-web-ui
    networks:
      - typingrealm-net
    build:
      context: ./typingrealm-web
      dockerfile: Dockerfile
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 750m
