version: '3.4'

networks:
  dev-typingrealm-net:

services:
  dev-typingrealm-identityserver:
    image: ${DOCKER_REGISTRY-}dev-typingrealm-identityserver
    container_name: dev-typingrealm-identityserver
    networks:
      - dev-typingrealm-net
    build:
      context: .
      dockerfile: TypingRealm.IdentityServer.Host/Dockerfile
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 750m
    env_file:
      - .env.dev

  dev-typingrealm-profiles:
    image: ${DOCKER_REGISTRY-}dev-typingrealm-profiles
    container_name: dev-typingrealm-profiles
    networks:
      - dev-typingrealm-net
    build:
      context: .
      dockerfile: TypingRealm.Profiles.Api/Dockerfile
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 750m
    env_file:
      - .env.dev

  dev-typingrealm-data:
    image: ${DOCKER_REGISTRY-}dev-typingrealm-data
    container_name: dev-typingrealm-data
    networks:
      - dev-typingrealm-net
    build:
      context: .
      dockerfile: TypingRealm.Data.Api/Dockerfile
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 750m
    env_file:
      - .env.dev

  # === Infrastructure ===

  dev-typingrealm-postgres:
    image: postgres
    container_name: dev-typingrealm-postgres
    networks:
      - dev-typingrealm-net
    ports:
      - 5432:5432
    volumes:
      - ./infrastructure-data/dev/postgres:/var/lib/postgresql/data
    restart: unless-stopped
    mem_limit: 2g
    mem_reservation: 1.75g
    env_file:
      - .env.dev

  dev-typingrealm-redis:
    image: redis
    container_name: dev-typingrealm-redis
    networks:
      - dev-typingrealm-net
    ports:
      - 6379:6379
    volumes:
      - ./infrastructure-data/dev/redis:/data
    restart: unless-stopped
    mem_limit: 2g
    mem_reservation: 1.75g
    env_file:
      - .env.dev

  # Simple local UI test page to facilitate BackEnd development.
  dev-typingrealm-web-ui:
    image: ${DOCKER_REGISTRY-}dev-typingrealm-web-ui
    container_name: dev-typingrealm-web-ui
    networks:
      - dev-typingrealm-net
    build:
      context: ./typingrealm-web
      dockerfile: Dockerfile
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 750m
    env_file:
      - .env.dev
