version: '3.4'

networks:
  typingrealm-identityserver-net:
  typingrealm-texts-net:
  typingrealm-library-net:
  typingrealm-typing-net:
  typingrealm-typingduels-net:
  typingrealm-profiles-net:
  typingrealm-data-net:
  typingrealm-web-ui-net:
  typingrealm-net:
  local-tyr_local-typingrealm-net:
    external: true
  dev-tyr_dev-typingrealm-net:
    external: true
  infra-tyr_typingrealm-infra-net:
    external: true

services:
  typingrealm-data:
    image: ${DOCKER_REGISTRY-}typingrealm-data
    container_name: typingrealm-data
    networks:
      - typingrealm-net
      - infra-tyr_typingrealm-infra-net
      - typingrealm-data-net
    volumes:
      - ./infrastructure-data/prod/data/logs:/app/logs
    build:
      context: .
      dockerfile: TypingRealm.Data.Api/Dockerfile
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 750m
    env_file:
      - deployment/.env
      - deployment/.env.prod
      - deployment/.env.prod.data

  typingrealm-data-postgres:
    image: postgres
    container_name: typingrealm-data-postgres
    networks:
      - typingrealm-data-net
    ports:
      - 13032:5432
    volumes:
      - ./infrastructure-data/prod/data/postgres:/var/lib/postgresql/data
    restart: unless-stopped
    mem_limit: 2g
    mem_reservation: 1.5g
    env_file:
      - deployment/.env
      - deployment/.env.prod
      - deployment/.env.prod.data

  typingrealm-data-redis:
    image: redis
    container_name: typingrealm-data-redis
    networks:
      - typingrealm-data-net
    ports:
      - 13079:6379
    volumes:
      - ./infrastructure-data/prod/data/redis:/data
    restart: unless-stopped
    mem_limit: 2g
    mem_reservation: 1.5g
    env_file:
      - deployment/.env
      - deployment/.env.prod
      - deployment/.env.prod.data

  typingrealm-identityserver:
    image: ${DOCKER_REGISTRY-}typingrealm-identityserver
    container_name: typingrealm-identityserver
    networks:
      - typingrealm-net
      - infra-tyr_typingrealm-infra-net
      - typingrealm-identityserver-net
    volumes:
      - ./infrastructure-data/prod/identityserver/logs:/app/logs
    build:
      context: .
      dockerfile: TypingRealm.IdentityServer.Host/Dockerfile
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 750m
    env_file:
      - deployment/.env
      - deployment/.env.prod
      - deployment/.env.prod.identityserver

  typingrealm-library:
    image: ${DOCKER_REGISTRY-}typingrealm-library
    container_name: typingrealm-library
    networks:
      - typingrealm-net
      - infra-tyr_typingrealm-infra-net
      - typingrealm-library-net
    volumes:
      - ./infrastructure-data/prod/library/logs:/app/logs
    build:
      context: .
      dockerfile: TypingRealm.Library.Api/Dockerfile
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 750m
    env_file:
      - deployment/.env
      - deployment/.env.prod
      - deployment/.env.prod.library

  typingrealm-library-postgres:
    image: postgres
    container_name: typingrealm-library-postgres
    networks:
      - typingrealm-library-net
    ports:
      - 11132:5432
    volumes:
      - ./infrastructure-data/prod/library/postgres:/var/lib/postgresql/data
    restart: unless-stopped
    mem_limit: 2g
    mem_reservation: 1.5g
    env_file:
      - deployment/.env
      - deployment/.env.prod
      - deployment/.env.prod.library

  typingrealm-profiles:
    image: ${DOCKER_REGISTRY-}typingrealm-profiles
    container_name: typingrealm-profiles
    networks:
      - typingrealm-net
      - infra-tyr_typingrealm-infra-net
      - typingrealm-profiles-net
    volumes:
      - ./infrastructure-data/prod/profiles/logs:/app/logs
    build:
      context: .
      dockerfile: TypingRealm.Profiles.Api/Dockerfile
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 750m
    env_file:
      - deployment/.env
      - deployment/.env.prod
      - deployment/.env.prod.profiles

  typingrealm-texts:
    image: ${DOCKER_REGISTRY-}typingrealm-texts
    container_name: typingrealm-texts
    networks:
      - typingrealm-net
      - infra-tyr_typingrealm-infra-net
      - typingrealm-texts-net
    volumes:
      - ./infrastructure-data/prod/texts/logs:/app/logs
    build:
      context: .
      dockerfile: TypingRealm.Texts.Api/Dockerfile
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 750m
    env_file:
      - deployment/.env
      - deployment/.env.prod
      - deployment/.env.prod.texts

  typingrealm-texts-redis:
    image: redis
    container_name: typingrealm-texts-redis
    networks:
      - typingrealm-texts-net
    ports:
      - 11079:6379
    volumes:
      - ./infrastructure-data/prod/texts/redis:/data
    restart: unless-stopped
    mem_limit: 2g
    mem_reservation: 1.5g
    env_file:
      - deployment/.env
      - deployment/.env.prod
      - deployment/.env.prod.texts

  typingrealm-typing:
    image: ${DOCKER_REGISTRY-}typingrealm-typing
    container_name: typingrealm-typing
    networks:
      - typingrealm-net
      - infra-tyr_typingrealm-infra-net
      - typingrealm-typing-net
    volumes:
      - ./infrastructure-data/prod/typing/logs:/app/logs
    build:
      context: .
      dockerfile: TypingRealm.Typing.Api/Dockerfile
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 750m
    env_file:
      - deployment/.env
      - deployment/.env.prod
      - deployment/.env.prod.typing

  typingrealm-typing-postgres:
    image: postgres
    container_name: typingrealm-typing-postgres
    networks:
      - typingrealm-net
      - infra-tyr_typingrealm-infra-net
      - typingrealm-typing-net
    ports:
      - 11232:5432
    volumes:
      - ./infrastructure-data/prod/typing/postgres:/var/lib/postgresql/data
    restart: unless-stopped
    mem_limit: 2g
    mem_reservation: 1.5g
    env_file:
      - deployment/.env
      - deployment/.env.prod
      - deployment/.env.prod.typing

  typingrealm-typing-redis:
    image: redis
    container_name: typingrealm-typing-redis
    networks:
      - typingrealm-net
      - infra-tyr_typingrealm-infra-net
      - typingrealm-typing-net
    ports:
      - 11279:6379
    volumes:
      - ./infrastructure-data/prod/typing/redis:/data
    restart: unless-stopped
    mem_limit: 2g
    mem_reservation: 1.5g
    env_file:
      - deployment/.env
      - deployment/.env.prod
      - deployment/.env.prod.typing

  typingrealm-typingduels:
    image: ${DOCKER_REGISTRY-}typingrealm-typingduels
    container_name: typingrealm-typingduels
    networks:
      - typingrealm-net
      - infra-tyr_typingrealm-infra-net
      - typingrealm-typingduels-net
    volumes:
      - ./infrastructure-data/prod/typingduels/logs:/app/logs
    build:
      context: .
      dockerfile: TypingRealm.TypingDuels.Api/Dockerfile
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 750m
    env_file:
      - deployment/.env
      - deployment/.env.prod
      - deployment/.env.prod.typingduels

  typingrealm-typingduels-postgres:
    image: postgres
    container_name: typingrealm-typingduels-postgres
    networks:
      - typingrealm-typingduels-net
    ports:
      - 11332:5432
    volumes:
      - ./infrastructure-data/prod/typingduels/postgres:/var/lib/postgresql/data
    restart: unless-stopped
    mem_limit: 2g
    mem_reservation: 1.5g
    env_file:
      - deployment/.env
      - deployment/.env.prod
      - deployment/.env.prod.typingduels

  typingrealm-typingduels-redis:
    image: redis
    container_name: typingrealm-typingduels-redis
    networks:
      - typingrealm-typingduels-net
    ports:
      - 11379:6379
    volumes:
      - ./infrastructure-data/prod/typingduels/redis:/data
    restart: unless-stopped
    mem_limit: 2g
    mem_reservation: 1.5g
    env_file:
      - deployment/.env
      - deployment/.env.prod
      - deployment/.env.prod.typingduels

  typingrealm-web-ui:
    image: ${DOCKER_REGISTRY-}typingrealm-web-ui
    container_name: typingrealm-web-ui
    networks:
      - typingrealm-net
      - infra-tyr_typingrealm-infra-net
      - typingrealm-web-ui-net
    volumes:
      - ./infrastructure-data/prod/web-ui/logs:/app/logs
    build:
      context: ./typingrealm-web
      dockerfile: Dockerfile
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 750m
    env_file:
      - deployment/.env
      - deployment/.env.prod


  typingrealm-caddy:
    image: caddy
    container_name: typingrealm-caddy
    networks:
      - typingrealm-net
      - local-tyr_local-typingrealm-net
      - dev-tyr_dev-typingrealm-net
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./reverse-proxy/Caddyfile.host:/etc/caddy/Caddyfile
      - ./infrastructure-data/prod/caddy_data:/data
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 750m
    env_file:
      - deployment/.env.prod
