version: '3.4'

networks:
  dev-typingrealm-identityserver-net:
  dev-typingrealm-texts-net:
  dev-typingrealm-library-net:
  dev-typingrealm-typing-net:
  dev-typingrealm-typingduels-net:
  dev-typingrealm-profiles-net:
  dev-typingrealm-data-net:
  dev-typingrealm-web-ui-net:
  dev-typingrealm-net:
  infra-tyr_typingrealm-infra-net:
    external: true

services:
  dev-typingrealm-data:
    image: ${DOCKER_REGISTRY-}dev-typingrealm-data
    container_name: dev-typingrealm-data
    networks:
      - dev-typingrealm-net
      - infra-tyr_typingrealm-infra-net
      - dev-typingrealm-data-net
    volumes:
      - ./infrastructure-data/dev/data/logs:/app/logs
    build:
      context: .
      dockerfile: TypingRealm.Data.Api/Dockerfile
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 750m
    env_file:
      - deployment/.env
      - deployment/.env.dev
      - deployment/.env.dev.data

  dev-typingrealm-data-postgres:
    image: postgres
    container_name: dev-typingrealm-data-postgres
    networks:
      - dev-typingrealm-data-net
    ports:
      - 33032:5432
    volumes:
      - ./infrastructure-data/dev/data/postgres:/var/lib/postgresql/data
    restart: unless-stopped
    mem_limit: 2g
    mem_reservation: 1.5g
    env_file:
      - deployment/.env
      - deployment/.env.dev
      - deployment/.env.dev.data

  dev-typingrealm-data-redis:
    image: redis
    container_name: dev-typingrealm-data-redis
    networks:
      - dev-typingrealm-data-net
    ports:
      - 33079:6379
    volumes:
      - ./infrastructure-data/dev/data/redis:/data
    restart: unless-stopped
    mem_limit: 2g
    mem_reservation: 1.5g
    env_file:
      - deployment/.env
      - deployment/.env.dev
      - deployment/.env.dev.data

  dev-typingrealm-identityserver:
    image: ${DOCKER_REGISTRY-}dev-typingrealm-identityserver
    container_name: dev-typingrealm-identityserver
    networks:
      - dev-typingrealm-net
      - infra-tyr_typingrealm-infra-net
      - dev-typingrealm-identityserver-net
    volumes:
      - ./infrastructure-data/dev/identityserver/logs:/app/logs
    build:
      context: .
      dockerfile: TypingRealm.IdentityServer.Host/Dockerfile
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 750m
    env_file:
      - deployment/.env
      - deployment/.env.dev
      - deployment/.env.dev.identityserver

  dev-typingrealm-library:
    image: ${DOCKER_REGISTRY-}dev-typingrealm-library
    container_name: dev-typingrealm-library
    networks:
      - dev-typingrealm-net
      - infra-tyr_typingrealm-infra-net
      - dev-typingrealm-library-net
    volumes:
      - ./infrastructure-data/dev/library/logs:/app/logs
    build:
      context: .
      dockerfile: TypingRealm.Library.Api/Dockerfile
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 750m
    env_file:
      - deployment/.env
      - deployment/.env.dev
      - deployment/.env.dev.library

  dev-typingrealm-library-postgres:
    image: postgres
    container_name: dev-typingrealm-library-postgres
    networks:
      - dev-typingrealm-library-net
    ports:
      - 31132:5432
    volumes:
      - ./infrastructure-data/dev/library/postgres:/var/lib/postgresql/data
    restart: unless-stopped
    mem_limit: 2g
    mem_reservation: 1.5g
    env_file:
      - deployment/.env
      - deployment/.env.dev
      - deployment/.env.dev.library

  dev-typingrealm-profiles:
    image: ${DOCKER_REGISTRY-}dev-typingrealm-profiles
    container_name: dev-typingrealm-profiles
    networks:
      - dev-typingrealm-net
      - infra-tyr_typingrealm-infra-net
      - dev-typingrealm-profiles-net
    volumes:
      - ./infrastructure-data/dev/profiles/logs:/app/logs
    build:
      context: .
      dockerfile: TypingRealm.Profiles.Api/Dockerfile
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 750m
    env_file:
      - deployment/.env
      - deployment/.env.dev
      - deployment/.env.dev.profiles

  dev-typingrealm-texts:
    image: ${DOCKER_REGISTRY-}dev-typingrealm-texts
    container_name: dev-typingrealm-texts
    networks:
      - dev-typingrealm-net
      - infra-tyr_typingrealm-infra-net
      - dev-typingrealm-texts-net
    volumes:
      - ./infrastructure-data/dev/texts/logs:/app/logs
    build:
      context: .
      dockerfile: TypingRealm.Texts.Api/Dockerfile
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 750m
    env_file:
      - deployment/.env
      - deployment/.env.dev
      - deployment/.env.dev.texts

  dev-typingrealm-texts-redis:
    image: redis
    container_name: dev-typingrealm-texts-redis
    networks:
      - dev-typingrealm-texts-net
    ports:
      - 31079:6379
    volumes:
      - ./infrastructure-data/dev/texts/redis:/data
    restart: unless-stopped
    mem_limit: 2g
    mem_reservation: 1.5g
    env_file:
      - deployment/.env
      - deployment/.env.dev
      - deployment/.env.dev.texts

  dev-typingrealm-typing:
    image: ${DOCKER_REGISTRY-}dev-typingrealm-typing
    container_name: dev-typingrealm-typing
    networks:
      - dev-typingrealm-net
      - infra-tyr_typingrealm-infra-net
      - dev-typingrealm-typing-net
    volumes:
      - ./infrastructure-data/dev/typing/logs:/app/logs
    build:
      context: .
      dockerfile: TypingRealm.Typing.Api/Dockerfile
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 750m
    env_file:
      - deployment/.env
      - deployment/.env.dev
      - deployment/.env.dev.typing

  dev-typingrealm-typing-postgres:
    image: postgres
    container_name: dev-typingrealm-typing-postgres
    networks:
      - dev-typingrealm-net
      - infra-tyr_typingrealm-infra-net
      - dev-typingrealm-typing-net
    ports:
      - 31232:5432
    volumes:
      - ./infrastructure-data/dev/typing/postgres:/var/lib/postgresql/data
    restart: unless-stopped
    mem_limit: 2g
    mem_reservation: 1.5g
    env_file:
      - deployment/.env
      - deployment/.env.dev
      - deployment/.env.dev.typing

  dev-typingrealm-typing-redis:
    image: redis
    container_name: dev-typingrealm-typing-redis
    networks:
      - dev-typingrealm-net
      - infra-tyr_typingrealm-infra-net
      - dev-typingrealm-typing-net
    ports:
      - 31279:6379
    volumes:
      - ./infrastructure-data/dev/typing/redis:/data
    restart: unless-stopped
    mem_limit: 2g
    mem_reservation: 1.5g
    env_file:
      - deployment/.env
      - deployment/.env.dev
      - deployment/.env.dev.typing

  dev-typingrealm-typingduels:
    image: ${DOCKER_REGISTRY-}dev-typingrealm-typingduels
    container_name: dev-typingrealm-typingduels
    networks:
      - dev-typingrealm-net
      - infra-tyr_typingrealm-infra-net
      - dev-typingrealm-typingduels-net
    volumes:
      - ./infrastructure-data/dev/typingduels/logs:/app/logs
    build:
      context: .
      dockerfile: TypingRealm.TypingDuels.Api/Dockerfile
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 750m
    env_file:
      - deployment/.env
      - deployment/.env.dev
      - deployment/.env.dev.typingduels

  dev-typingrealm-typingduels-postgres:
    image: postgres
    container_name: dev-typingrealm-typingduels-postgres
    networks:
      - dev-typingrealm-typingduels-net
    ports:
      - 31332:5432
    volumes:
      - ./infrastructure-data/dev/typingduels/postgres:/var/lib/postgresql/data
    restart: unless-stopped
    mem_limit: 2g
    mem_reservation: 1.5g
    env_file:
      - deployment/.env
      - deployment/.env.dev
      - deployment/.env.dev.typingduels

  dev-typingrealm-typingduels-redis:
    image: redis
    container_name: dev-typingrealm-typingduels-redis
    networks:
      - dev-typingrealm-typingduels-net
    ports:
      - 31379:6379
    volumes:
      - ./infrastructure-data/dev/typingduels/redis:/data
    restart: unless-stopped
    mem_limit: 2g
    mem_reservation: 1.5g
    env_file:
      - deployment/.env
      - deployment/.env.dev
      - deployment/.env.dev.typingduels

  dev-typingrealm-web-ui:
    image: ${DOCKER_REGISTRY-}dev-typingrealm-web-ui
    container_name: dev-typingrealm-web-ui
    networks:
      - dev-typingrealm-net
      - infra-tyr_typingrealm-infra-net
      - dev-typingrealm-web-ui-net
    volumes:
      - ./infrastructure-data/dev/web-ui/logs:/app/logs
    build:
      context: ./typingrealm-web
      dockerfile: Dockerfile
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 750m
    env_file:
      - deployment/.env
      - deployment/.env.dev

