version: '3.4'

networks:
  typingrealm-identityserver-net:
  typingrealm-texts-net:
  typingrealm-library-net:
  typingrealm-profiles-net:
  typingrealm-data-net:
  typingrealm-web-ui-net:
  typingrealm-net:
  infra-tyr_typingrealm-infra-net:
    external: true

services:
  typingrealm-data:
    image: ${DOCKER_REGISTRY-}typingrealm-data
    container_name: typingrealm-data
    networks:
      - typingrealm-net
      - infra-tyr_typingrealm-infra-net
      - typingrealm-data-net
    build:
      context: .
      dockerfile: TypingRealm.Data.Api/Dockerfile
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 750m
    env_file:
      - deployment/.env
      - deployment/.env.prod
      - deployment/.env.prod.data

  typingrealm-data-postgres:
    image: postgres
    container_name: typingrealm-data-postgres
    networks:
      - typingrealm-data-net
    volumes:
      - ./infrastructure-data/prod/data/postgres:/var/lib/postgresql/data
    restart: unless-stopped
    mem_limit: 2g
    mem_reservation: 1.5g
    env_file:
      - deployment/.env
      - deployment/.env.prod
      - deployment/.env.prod.data

  typingrealm-data-redis:
    image: redis
    container_name: typingrealm-data-redis
    networks:
      - typingrealm-data-net
    volumes:
      - ./infrastructure-data/prod/data/redis:/data
    restart: unless-stopped
    mem_limit: 2g
    mem_reservation: 1.5g
    env_file:
      - deployment/.env
      - deployment/.env.prod
      - deployment/.env.prod.data

  typingrealm-identityserver:
    image: ${DOCKER_REGISTRY-}typingrealm-identityserver
    container_name: typingrealm-identityserver
    networks:
      - typingrealm-net
      - infra-tyr_typingrealm-infra-net
      - typingrealm-identityserver-net
    build:
      context: .
      dockerfile: TypingRealm.IdentityServer.Host/Dockerfile
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 750m
    env_file:
      - deployment/.env
      - deployment/.env.prod
      - deployment/.env.prod.identityserver

  typingrealm-library:
    image: ${DOCKER_REGISTRY-}typingrealm-library
    container_name: typingrealm-library
    networks:
      - typingrealm-net
      - infra-tyr_typingrealm-infra-net
      - typingrealm-library-net
    build:
      context: .
      dockerfile: TypingRealm.Library.Api/Dockerfile
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 750m
    env_file:
      - deployment/.env
      - deployment/.env.prod
      - deployment/.env.prod.library

  typingrealm-library-postgres:
    image: postgres
    container_name: typingrealm-library-postgres
    networks:
      - typingrealm-library-net
    volumes:
      - ./infrastructure-data/prod/library/postgres:/var/lib/postgresql/data
    restart: unless-stopped
    mem_limit: 2g
    mem_reservation: 1.5g
    env_file:
      - deployment/.env
      - deployment/.env.prod
      - deployment/.env.prod.library

  typingrealm-profiles:
    image: ${DOCKER_REGISTRY-}typingrealm-profiles
    container_name: typingrealm-profiles
    networks:
      - typingrealm-net
      - infra-tyr_typingrealm-infra-net
      - typingrealm-profiles-net
    build:
      context: .
      dockerfile: TypingRealm.Profiles.Api/Dockerfile
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 750m
    env_file:
      - deployment/.env
      - deployment/.env.prod
      - deployment/.env.prod.profiles

  typingrealm-texts:
    image: ${DOCKER_REGISTRY-}typingrealm-texts
    container_name: typingrealm-texts
    networks:
      - typingrealm-net
      - infra-tyr_typingrealm-infra-net
      - typingrealm-texts-net
    build:
      context: .
      dockerfile: TypingRealm.Texts.Api/Dockerfile
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 750m
    env_file:
      - deployment/.env
      - deployment/.env.prod
      - deployment/.env.prod.texts

  typingrealm-texts-redis:
    image: redis
    container_name: typingrealm-texts-redis
    networks:
      - typingrealm-texts-net
    volumes:
      - ./infrastructure-data/prod/texts/redis:/data
    restart: unless-stopped
    mem_limit: 2g
    mem_reservation: 1.5g
    env_file:
      - deployment/.env
      - deployment/.env.prod
      - deployment/.env.prod.texts

  typingrealm-web-ui:
    image: ${DOCKER_REGISTRY-}typingrealm-web-ui
    container_name: typingrealm-web-ui
    networks:
      - typingrealm-net
      - infra-tyr_typingrealm-infra-net
      - typingrealm-web-ui-net
    build:
      context: ./typingrealm-web
      dockerfile: Dockerfile
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 750m
    env_file:
      - deployment/.env
      - deployment/.env.prod


  typingrealm-caddy:
    image: caddy
    container_name: typingrealm-caddy
    networks:
      - typingrealm-net
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./reverse-proxy/Caddyfile.prod:/etc/caddy/Caddyfile
      - ./infrastructure-data/prod/caddy_data:/data
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 750m
    env_file:
      - deployment/.env.prod
