FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY .editorconfig .
COPY Directory.Build.props .
COPY ["texts/dotnet/TypingRealm.Texts.Api/TypingRealm.Texts.Api.csproj", "TypingRealm.Texts.Api/"]
RUN dotnet restore "TypingRealm.Texts.Api/TypingRealm.Texts.Api.csproj"
COPY texts/dotnet .
WORKDIR "/src/TypingRealm.Texts.Api"
RUN dotnet build "TypingRealm.Texts.Api.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "TypingRealm.Texts.Api.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "TypingRealm.Texts.Api.dll"]