FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY .editorconfig .
COPY Directory.Build.props .
COPY ["framework/dotnet/TypingRealm.Hosting/TypingRealm.Hosting.csproj", "framework/dotnet/TypingRealm.Hosting/"]
COPY ["texts/dotnet/TypingRealm.Texts.Api/TypingRealm.Texts.Api.csproj", "texts/dotnet/TypingRealm.Texts.Api/"]
WORKDIR /src/texts/dotnet
RUN dotnet restore "TypingRealm.Texts.Api/TypingRealm.Texts.Api.csproj"
WORKDIR /src
COPY framework/dotnet framework/dotnet/
COPY texts/dotnet texts/dotnet/
WORKDIR "/src/texts/dotnet/TypingRealm.Texts.Api"
RUN dotnet build "TypingRealm.Texts.Api.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "TypingRealm.Texts.Api.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish ./service/bin
COPY texts/config-dev.json ./config.json
WORKDIR /app/service/bin
ENTRYPOINT ["dotnet", "TypingRealm.Texts.Api.dll"]
