FROM node:18

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install
#RUN npm ci --only=production

COPY ./app .
COPY ./app/config/config-local.js ./config/config.js

CMD [ "node", "index.js" ]
