FROM node:18

RUN curl -fsSL -o /usr/local/bin/dbmate https://github.com/amacneil/dbmate/releases/latest/download/dbmate-linux-amd64
RUN chmod +x /usr/local/bin/dbmate

WORKDIR /usr/src/app

COPY package*.json ./

#RUN npm install
RUN npm ci --only=production

COPY ./app .
COPY ./db ./db
COPY ./app/config/config-production.js ./config/config.js

CMD [ "npm", "run", "start:prod" ]
