version: '3.4'

networks:
  typingrealm-net:
  typingrealm-typing-net:
  typingrealm-ui-net:

services:
  typingrealm-typing:
    image: ${DOCKER_REGISTRY-}typingrealm-typing
    container_name: typingrealm-typing
    networks:
      - typingrealm-net
      - typingrealm-typing-net
    build:
      context: ./backend-node
      dockerfile: Dockerfile-production
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 750m
    environment:
      - DATABASE_URL=postgres://postgres:admin@typingrealm-typing-postgres:5432/typing?sslmode=disable

  typingrealm-typing-postgres:
    image: postgres
    container_name: typingrealm-typing-postgres
    networks:
      - typingrealm-net
      - typingrealm-typing-net
    volumes:
      - ./infrastructure-data/production/typing/postgres:/var/lib/postgresql/data
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 750m

  typingrealm-ui:
    image: ${DOCKER_REGISTRY-}typingrealm-ui
    container_name: typingrealm-ui
    networks:
      - typingrealm-net
      - typingrealm-ui-net
    build:
      context: ./frontend
      dockerfile: Dockerfile-production
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 750m
