version: '3.4'

networks:
  typingrealm-net:
  typingrealm-typing-net:
  typingrealm-texts-net:
  typingrealm-ui-net:

services:
  typingrealm-typing-api:
    image: caddy
    container_name: typingrealm-typing-api
    networks:
      - typingrealm-net
      - typingrealm-typing-net
    volumes:
      - ./backend/typing/Caddyfile-production:/etc/caddy/Caddyfile
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 750m

  typingrealm-typing-node:
    image: ${DOCKER_REGISTRY-}typingrealm-typing-node
    container_name: typingrealm-typing-node
    networks:
      - typingrealm-net
      - typingrealm-typing-net
    build:
      context: ./backend
      dockerfile: typing/node/Dockerfile-production
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 750m
    environment:
      - DATABASE_URL=postgres://postgres:admin@typingrealm-typing-postgres:5432/typing?sslmode=disable
      - CACHE_URL=redis://typingrealm-typing-redis:6379

  typingrealm-typing-node-2:
    image: ${DOCKER_REGISTRY-}typingrealm-typing-node
    container_name: typingrealm-typing-node-2
    networks:
      - typingrealm-net
      - typingrealm-typing-net
    build:
      context: ./backend
      dockerfile: typing/node/Dockerfile-production
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 750m
    environment:
      - DATABASE_URL=postgres://postgres:admin@typingrealm-typing-postgres:5432/typing?sslmode=disable
      - CACHE_URL=redis://typingrealm-typing-redis:6379

  typingrealm-typing-node-3:
    image: ${DOCKER_REGISTRY-}typingrealm-typing-node
    container_name: typingrealm-typing-node-3
    networks:
      - typingrealm-net
      - typingrealm-typing-net
    build:
      context: ./backend
      dockerfile: typing/node/Dockerfile-production
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 750m
    environment:
      - DATABASE_URL=postgres://postgres:admin@typingrealm-typing-postgres:5432/typing?sslmode=disable
      - CACHE_URL=redis://typingrealm-typing-redis:6379

  typingrealm-typing-postgres:
    image: postgres
    container_name: typingrealm-typing-postgres
    networks:
      - typingrealm-net
      - typingrealm-typing-net
    ports:
      - 11432:5432
    volumes:
      - ./infrastructure-data/production/typing/postgres:/var/lib/postgresql/data
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 750m
    environment:
      - POSTGRES_PASSWORD=admin

  typingrealm-typing-redis:
    image: redis
    container_name: typingrealm-typing-redis
    networks:
      - typingrealm-net
      - typingrealm-typing-net
    ports:
      - 11379:6379
    volumes:
      - ./infrastructure-data/production/typing/redis:/data
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 750m

  typingrealm-texts-api:
    image: caddy
    container_name: typingrealm-texts-api
    networks:
      - typingrealm-net
      - typingrealm-texts-net
    volumes:
      - ./backend/texts/Caddyfile-production:/etc/caddy/Caddyfile
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 750m

  typingrealm-texts-node:
    image: ${DOCKER_REGISTRY-}typingrealm-texts-node
    container_name: typingrealm-texts-node
    networks:
      - typingrealm-net
      - typingrealm-texts-net
    build:
      context: ./backend
      dockerfile: texts/node/Dockerfile-production
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 750m

  typingrealm-texts-node-2:
    image: ${DOCKER_REGISTRY-}typingrealm-texts-node
    container_name: typingrealm-texts-node-2
    networks:
      - typingrealm-net
      - typingrealm-texts-net
    build:
      context: ./backend
      dockerfile: texts/node/Dockerfile-production
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 750m

  typingrealm-texts-node-3:
    image: ${DOCKER_REGISTRY-}typingrealm-texts-node
    container_name: typingrealm-texts-node-3
    networks:
      - typingrealm-net
      - typingrealm-texts-net
    build:
      context: ./backend
      dockerfile: texts/node/Dockerfile-production
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 750m

  typingrealm-texts-dotnet:
    image: ${DOCKER_REGISTRY-}typingrealm-texts-dotnet
    container_name: typingrealm-texts-dotnet
    networks:
      - typingrealm-net
      - typingrealm-texts-net
    build:
      context: ./backend
      dockerfile: texts/dotnet/Dockerfile-production
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 750m

  typingrealm-texts-dotnet-2:
    image: ${DOCKER_REGISTRY-}typingrealm-texts-dotnet
    container_name: typingrealm-texts-dotnet-2
    networks:
      - typingrealm-net
      - typingrealm-texts-net
    build:
      context: ./backend
      dockerfile: texts/dotnet/Dockerfile-production
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 750m

  typingrealm-texts-dotnet-3:
    image: ${DOCKER_REGISTRY-}typingrealm-texts-dotnet
    container_name: typingrealm-texts-dotnet-3
    networks:
      - typingrealm-net
      - typingrealm-texts-net
    build:
      context: ./backend
      dockerfile: texts/dotnet/Dockerfile-production
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 750m

  typingrealm-ui:
    image: ${DOCKER_REGISTRY-}typingrealm-ui
    container_name: typingrealm-ui
    networks:
      - typingrealm-net
      - typingrealm-ui-net
    build:
      context: ./frontend
      dockerfile: Dockerfile-production
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 750m
