version: '3.4'

networks:
  dev-typingrealm-net:
  dev-typingrealm-typing-net:
  dev-typingrealm-ui-net:

services:
  dev-typingrealm-typing:
    image: ${DOCKER_REGISTRY-}dev-typingrealm-typing
    container_name: dev-typingrealm-typing
    networks:
      - dev-typingrealm-net
      - dev-typingrealm-typing-net
    build:
      context: ./backend-node
      dockerfile: Dockerfile-dev
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 750m

  dev-typingrealm-ui:
    image: ${DOCKER_REGISTRY-}dev-typingrealm-ui
    container_name: dev-typingrealm-ui
    networks:
      - dev-typingrealm-net
      - dev-typingrealm-ui-net
    build:
      context: ./frontend
      dockerfile: Dockerfile-dev
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 750m
