version: '3.4'

networks:
  local-typingrealm-net:
  local-typingrealm-typing-net:
  local-typingrealm-ui-net:
  dev-tyr_dev-typingrealm-net:
    external: true

services:
  local-typingrealm-typing:
    image: ${DOCKER_REGISTRY-}local-typingrealm-typing
    container_name: local-typingrealm-typing
    networks:
      - local-typingrealm-net
      - local-typingrealm-typing-net
      - dev-tyr_dev-typingrealm-net
    ports:
      - 30101:80
    build:
      context: ./backend-node
      dockerfile: Dockerfile-local
    volumes:
      - ./backend-node:/usr/src/app
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 750m

  local-typingrealm-ui:
    image: ${DOCKER_REGISTRY-}local-typingrealm-ui
    container_name: local-typingrealm-ui
    networks:
      - local-typingrealm-net
      - local-typingrealm-ui-net
    ports:
      - 30080:80
    build:
      context: ./frontend
      dockerfile: Dockerfile-local
    volumes:
      - ./frontend:/usr/share/nginx/html
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 750m
