version: '3.4'

networks:
  local-typingrealm-net:
  local-typingrealm-typing-net:
  local-typingrealm-texts-net:
  local-typingrealm-ui-net:
  dev-tyr_dev-typingrealm-net:
    external: true

services:
  local-typingrealm-typing-node:
    image: ${DOCKER_REGISTRY-}local-typingrealm-typing-node
    container_name: local-typingrealm-typing-node
    networks:
      - local-typingrealm-net
      - local-typingrealm-typing-net
      - dev-tyr_dev-typingrealm-net
    ports:
      - 30101:80
      - 50101:9229
    build:
      context: ./backend
      dockerfile: typing/node/Dockerfile-local
    volumes:
      - ./backend/framework/node:/usr/src/app/framework/node
      - ./backend/typing/node:/usr/src/app/typing/node
      - ./backend/typing/config.json:/usr/src/app/typing/config.json
      - /usr/src/app/typing/node/node_modules/
      - /usr/src/app/framework/node/configuration/node_modules/
      - /usr/src/app/framework/node/host/node_modules/
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 750m
    environment:
      - DATABASE_URL=postgres://postgres:admin@dev-typingrealm-typing-postgres:5432/typing?sslmode=disable
      - CACHE_URL=redis://dev-typingrealm-typing-redis:6379



  local-typingrealm-texts-node:
    image: ${DOCKER_REGISTRY-}local-typingrealm-texts-node
    container_name: local-typingrealm-texts-node
    networks:
      - local-typingrealm-net
      - local-typingrealm-texts-net
    ports:
      - 30102:80
      - 50102:9229
    build:
      context: ./backend
      dockerfile: texts/node/Dockerfile-local
    volumes:
      - ./backend/framework/node:/usr/src/app/framework/node
      - ./backend/texts/node:/usr/src/app/texts/node
      - ./backend/texts/config.json:/usr/src/app/texts/config.json
      - /usr/src/app/texts/node/node_modules/
      - /usr/src/app/framework/node/configuration/node_modules/
      - /usr/src/app/framework/node/host/node_modules/
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 750m

  local-typingrealm-ui:
    image: ${DOCKER_REGISTRY-}local-typingrealm-ui
    container_name: local-typingrealm-ui
    networks:
      - local-typingrealm-net
      - local-typingrealm-ui-net
    ports:
      - 30080:80
    build:
      context: ./frontend
      dockerfile: Dockerfile-local
    volumes:
      - ./frontend:/usr/share/nginx/html
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 750m
