FROM node:18

RUN curl -fsSL -o /usr/local/bin/dbmate https://github.com/amacneil/dbmate/releases/latest/download/dbmate-linux-amd64
RUN chmod +x /usr/local/bin/dbmate

WORKDIR /usr/src/app

COPY typing-node/package*.json ./

RUN npm install
#RUN npm ci --only=production

COPY typing-node/app app/
COPY typing-node/app/config/config-dev.js app/config/config.js
COPY db db/

CMD [ "npm", "run", "start:prod" ]
